name: MinnieSkates
favicon: null
layout_spectrum: 0.8082160195335746
typography_spectrum: 0.48542
title: Minnie the Skating Pup
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#030104'
    - '#4a515b'
    - '#dae3e8'
    - '#d8a786'
    - '#a17d4d'
  brandStrength: 0.5
  lightness: 0.4375
  saturation: 0.75
  rhythmicContrast: 0.6910578089300543
purpose: []
